apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap.yaml
data:
  DB_NAME: coworking-project
  DB_USER: admin
  DB_HOST: postgresql-service
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: bXlwYXNzd29yZA==